#!/usr/bin/env Rscript

####################################
# Author: Pantakan Puengrang
# Corresponding Author: Kanthida Kusonmano
# Affiliation: Systems Biology and Bioinformatics Research Group, KMUTT, Thailand
# Used for: Beginner's guide to microbiome analysis tutorial, CSBio2020
# Reference: Uthaipaisanwong, P., et al. (2020). “Beginner’s guide to microbiome analysis: Bioinformatics guidelines and practical concepts for amplicon-based microbiome analysis” In CSBio’20: Proceedings of the Eleventh International Conference on Computational Systems-Biology and Bioinformatics (CSBio2020), November 19– 21, 2020, Bangkok, Thailand. ACM, New York, NY, USA, 3 pages. https: //doi.org/10.1145/3429210.3429211
# Last modified date: November 17, 2020
####################################

####################################
# Rarefaction curves visualization
####################################

# -----------------------------------
# Load R library for visualization
# -----------------------------------
library(ggplot2)
library(dplyr)
library(stringr)
library(reshape2)
library(RColorBrewer)

# -----------------------------------
# Set visualization theme
# -----------------------------------
theme_set(theme_bw())

## Call the functions for microbiome data analysis
source("tutorial_scripts/microbiome_scripts.R")

# Set a path for input rarefaction information file that is generated by mothur
rare_mothur_file = "tutorial_inputs/tutorial.groups.rarefaction"

# Retrieve and prepare rarefaction data (from mothur) for visualization
rareData = import_mothur_rarefaction(rare_mothur_file)

## Plot Data
png('tutorial.rarefaction.png', width=3000, height=2800, res=300)
ggplot(rareData, aes(numsampled, value, color = variable)) +
  geom_line(size = 1) + # Thicknest of the line could be changed
  labs(x = "Sampling depth", y= "Number of features") +
  guides(color = guide_legend("Sample names"))
dev.off()
