#!/usr/bin/env Rscript

####################################
# Author: Pantakan Puengrang
# Modified Date: 28th October 2020
####################################

####################################
# Rarefaction curves visualization
####################################

# -----------------------------------
# Import library for visualization
# -----------------------------------
library(ggplot2)
library(dplyr)
library(stringr)
library(reshape2)
library(RColorBrewer)

# -----------------------------------
# Set theme
# -----------------------------------
theme_set(theme_bw())

## Get microbiome transformation and visualization functions
source("tutorial_scripts/microbiome_scripts.R")

# Import rarefaction information generated by mothur
rare_mothur_file = "tutorial_inputs/tutorial.groups.rarefaction"

# Import and Prepare data for visualization
rareData = import_mothur_rarefaction(rare_mothur_file)

## Plot Data
png('tutorial.rarefaction.png', width=3000, height=2800, res=300)
ggplot(rareData, aes(numsampled, value, color = variable)) +
  geom_line(size = 1) + # Thicknest of the line could be changed
  labs(x = "Sampling depth", y= "Number of features") +
  guides(color = guide_legend("Sample names"))
dev.off()

# Finish